### ISSUE TITLE
Currently played game shows "In non-Steam game: given_gameid"

### ISSUE THREAD

**Issue by k4rli** [DakshMiglani/Idler#2]
If I want to idle CSGO for example, I'd put gameId to 730. 
`var user = new Idler('my_username', 'my_password', '730', {method: 'manual'})`

I'd expect it to show up as 
`In-game`
`Counter-Strike: Global Offensive`, 
but it shows up as 
`In non-Steam game`
`730`

I don't think this is supposed to be normal.

**Comment by Zeziroth** [comment]
You have to give the gameID as an INT not as a STRING

It's just a fault in your usage :)
